### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by juraj-hrivnak** [FalsePattern/Triangulator#1]
[crash-2022-03-05_11.53.19-client.txt](https://github.com/FalsePattern/Triangulator/files/8190507/crash-2022-03-05_11.53.19-client.txt)
[2022-03-05-1.log](https://github.com/FalsePattern/Triangulator/files/8190508/2022-03-05-1.log)

I have a really big mod list though. I will try to reduce it to the minimum.
Could it be optifine?

**Comment by DarianLStephens** [comment]
It would be really nice if they would be uploaded to pastebin. I don't think many people are comfortable/can be bothered downloading files like that.
If it's anything like what I've had, then it's from a variety of mods giving the same error:
`java.lang.NoClassDefFoundError: net/minecraft/client/renderer/Tessellator`

**Comment by Roadhog360** [comment]
Are you using FoamFix?

**Comment by DarianLStephens** [comment]
I found that FoamFix crashes unless you turn this off:
`B:tessellatorAlphaPassCrashFix=false`

**Comment by FalsePattern** [comment]
Fixed in [1.2.7](https://github.com/FalsePattern/Triangulator/releases/tag/1.2.7), will be available on curseforge in a few days
