### ISSUE TITLE
[Compatibility Request]: Redstone Paste preview rendering bug

### ISSUE THREAD

**Issue by Jerome226** [FalsePattern/Triangulator#10]
### OS

Windows

### GPU

NVIDIA

### Other mod's name

Redstone Paste

### Other mod's homepage

https://www.curseforge.com/minecraft/mc-mods/redstone-paste

### Other mod's license

All Rights Reserved

### Game log

no need

### Description

Basically there a small rendering bug with the preview of redstone paste mod
![image](https://user-images.githubusercontent.com/55724525/160265477-6b9b2112-df71-4044-a4c0-67bda8bb8a02.png)

### Existing Patches

- [X] This request is not for OptiFine
- [X] This request is not for FoamFix

**Comment by FalsePattern** [comment]
Fixed in 1.3.1
![image](https://user-images.githubusercontent.com/30945458/160278554-2a1d8745-5b80-4db7-bd19-9df0bc48f6d2.png)
