### ISSUE TITLE
[Visual] Glitch with vanilla leaves

### ISSUE THREAD

**Issue by Doenerstyle** [FalsePattern/Triangulator#12]
After creating a new world with Triangulator v1.4.0 and ExtrabiomesXL v3.16.4 (latest on CF), you can find a large tree with glitched leaves:

![2022-05-27_15 20 42](https://user-images.githubusercontent.com/103001779/170836762-a10caaf9-1199-45f2-8da1-13ce0c49fa34.png)
![2022-05-27_15 21 07](https://user-images.githubusercontent.com/103001779/170836772-682fc3bd-b41b-44c4-a3e2-3bc01db4102f.png)

ExtrabiomesXL is only required for the seed to work/tree to appear, after removing it (so it's only Triangulator and its dependencies left), the issue persists.
The same happens on Triangulator v1.3.2.
I'm using an **AMD RX 590 GPU**, running the latest driver version.

### World data
World download: **[Triangulator issue #12.zip](https://github.com/FalsePattern/Triangulator/files/8791563/Triangulator.issue.12.zip)** (ExtrabiomesXL already removed)
Seed: **1610235090443848682**
Location: **-189 92 259**

**Comment by FalsePattern** [comment]
I have also experienced this issue on my system, it has to do with the sheer amount of vertices being generated overflowing the minecraft buffer.
I have a vague plan on how to fix this issue, but for the time being the thing that worked for me is adding optifine, as it already does something to make the buffer larger.

**Comment by Doenerstyle** [comment]
Adding Optifine did indeed fix it.
I guess for now that is the way to go, but it would of course be awesome if you could fix it.

**Comment by FalsePattern** [comment]
i uploaded version [1.4.1-alpha0001](https://github.com/FalsePattern/Triangulator/releases/tag/1.4.1-alpha0001) with a possible fix for this bug.
Please test it and report back, and if it works, i'll include this fix in the planned 1.4.1 release this week
