### ISSUE TITLE
[Bug]: Optifine (D6) crash with Triangulator 1.4.3

### ISSUE THREAD

**Issue by tyrael93** [FalsePattern/Triangulator#15]
### OS

Linux/BSD

### GPU

AMD

### Game log

https://paste.ee/p/wRtVR

### Description

Testing on an empty instance, the latest version of Triangulator crashes at startup with optifine added. I've attached the crash.

Edit:
This, for some reason, does not seem to happen with Optifine version E7. Testing with Tesselator 1.4.3 + Optifine E7, there are no crashes. This is a problem, because E7 has exponentially less cross-mod compatibility than D6 and a much lower performance improvement because of the merging with the Shaders mod ages ago (Optifine D6 is the last version of the mod for 1.7 before the merge and thus the go-to version for anyone who doesn't use shaders.)

As always, thanks for all help on the subject.

**Comment by embeddedt** [comment]
> E7 has exponentially less cross-mod compatibility than D6 and a much lower performance improvement

Do you have a source for this, and is it still true if you do not enable shaders? I've used E7 for quite some time and haven't seen any compatibility issues. If this is true, I would definitely consider downgrading to D6.

**Comment by tyrael93** [comment]
>do you have a source for this, and is it still true if you do not enable shaders? I've used E7 for quite some time and haven't seen any compatibility issues. If this is true, I would definitely consider downgrading to D6.

Sure. The real main issue with E7 (other than general poorer performance) is the lost compatibility with fastcraft 1.2.3. I'll explain.
The short version is directly explained in the fastcraft's download itself, but the vague wording doesn't really give it justice. Basically, you get a large FPS boost (in my case ranging roughly to 10-20+ additional fps) with fastcraft 1.2.3 compared to 1.2.5. Basically Player didn't really want to mess around with trying to fixing issues in a closed source mod for what in 2018 was already considered an ancient version, so he just ripped the offending parts apart from his mod until it stopped crashing with optifine.
![fast](https://user-images.githubusercontent.com/5557920/172787843-0f8185bf-4c50-4982-b130-dee5a4305031.png)

Adding default compat with the shaders mod required gutting a lot of the parts of fastcraft that had been jiggled together and tailored to work with optifine. Because of that fastcraft 1.2.3 outright crashes with newer version of optifine, but the cost of native shader support is a hefty FPS penalty compared to the original.

As it stands I can conjure a few random screenshots of similarly anecdotal evidence if needed, but if we stick to the provable facts (and let's face it, it's not like anyone made a study on cross-compatibility between those specific versions of optifine and fastcraft) shaders compaty = worse performance overall + loss of support. That's the long and short of it basically. I invite you to test that yourself (albeit, without tesselator for the time being :sweat_smile:) to see the difference.

**Comment by FalsePattern** [comment]
Should be fixed in 1.4.4

**Comment by tyrael93** [comment]
Confirmed, I've run the pack properly with 1.4.4 and haven't noticed any issue!
Thank you very much for your work :partying_face:
