### ISSUE TITLE
Add config for disabling features

### ISSUE THREAD

**Issue by makamys** [FalsePattern/Triangulator#16]
The mod implements multiple separate features, but currently there is no way to individually disable them. It would be nice if a config was added that let you do this.

As for motivation, there are several cases when the user may want to not have the triangulation feature enabled, but keep the rest of the fixes:
1. With my laptop's integrated graphics card (Intel HD Graphics 630), the triangulation has a negative impact on performance. I tested this in an instance with no other mods, on a superflat world with a render distance of 12, looking downwards from Y=208.
I got 215 FPS without the mod, and 156 with it. I believe @tyrael93's main GPU has comparable specs, so he can provide additional benchmarks on the matter if they are needed.
2. Some mods may be incompatible with triangulation. I can't name any that have been publicly released, but at the moment this is the case with a mod I'm working on.

**Comment by tyrael93** [comment]
I can indeed confirm that my specs are [vidrelated](https://www.youtube.com/watch?v=aSZYNhmLiqg) (not me, just found a guy that plays minecraft and has my same graphics card) and that I'm more than willing to benchmark performance finetuning that might benefit the lower end of the GPU spectrum.

**Comment by FalsePattern** [comment]
Added a config toggle in 1.5.0, it should fix the majority of the performance impact

**Comment by makamys** [comment]
I can confirm the new toggle works correctly. Disabling the setting restores my FPS to the 200s in the same benchmark, and also fixes the incompatibility with that mod I mentioned. :thumbsup:
