### ISSUE TITLE
improve the ugly grass

### ISSUE THREAD

**Issue by MiFliK** [FalsePattern/Triangulator#17]
![2022-06-13_02 13 55](https://user-images.githubusercontent.com/80956290/173253338-76b4018e-da6c-491a-a77c-5147fa0166cd.png)
Fixet 
![image](https://user-images.githubusercontent.com/80956290/173253407-ba725d39-a080-4767-aa62-01a0945efd8e.png)

**Comment by FalsePattern** [comment]
?

**Comment by embeddedt** [comment]
@FalsePattern 1.7.10 renders the grass plants a lot darker than 1.8 and newer versions do. You do have to be paying pretty close attention to notice it, though. I'm not sure if it's possible to fix this as I don't think the same rendering layers exist in 1.7.10.

**Comment by FalsePattern** [comment]
Ah, i see the problem now.
1.7.10 only has 2 main render layers for chunks, the opaque/cutout (regular rendering) and the translucent layer (water, stained glass, etc.), but that's mostly irrelevant to this issue.
From what i can see, the main difference between the two screenshots is that 1.7 adds the standard cardinal tinting to X-shaped plants too, while 1.8 just renders them with the color of the block they're on.
I'll dig up the plant rendering code and try removing the cardinal tinting from there.
