### ISSUE TITLE
[1.7.10] I can't Calibrate triangulator now

### ISSUE THREAD

**Issue by quentin452** [FalsePattern/Triangulator#28]
mods list : 

triangulator-mc1.7.10-1.7.5
SpongeMixins-1.5.0
falsepatternlib-mc1.7.10-0.10.5

logs :
[latest.log](https://github.com/FalsePattern/Triangulator/files/9438960/latest.log)

before applying calibration : 
![Capture d’écran_2022-08-28_03-59-50](https://user-images.githubusercontent.com/42176772/187054274-52366ebe-0f64-4ee9-9516-21ff201651b2.png)

after applying calibration : 
![Capture d’écran_2022-08-28_04-00-42](https://user-images.githubusercontent.com/42176772/187054277-73744414-fcc7-463a-ad25-05fd49989615.png)

**Comment by FalsePattern** [comment]
Does this message still appear when you restart the game/rejoin the world?

**Comment by quentin452** [comment]
ok
