### ISSUE TITLE
Weird Stars with Galacticraft.

### ISSUE THREAD

**Issue by DarianLStephens** [FalsePattern/Triangulator#3]
When the 'More Stars' option is enabled in Galacticraft core, this happens:
![2022-03-07_21 06 43](https://user-images.githubusercontent.com/15375876/157127543-32f8f546-1649-4031-941c-5457785688af.png)
![2022-03-07_21 06 49](https://user-images.githubusercontent.com/15375876/157127546-7f0ed5ed-3a69-4abc-a4d1-dcdacfacaf08.png)
![2022-03-07_22 23 45](https://user-images.githubusercontent.com/15375876/157127566-c651b0f1-d0b7-47a2-93a8-6109198f3d5c.png)
![2022-03-07_22 24 25](https://user-images.githubusercontent.com/15375876/157127569-1b0806e9-0266-4057-9d40-301cfd015075.png)
Without it, everything's normal, if less interesting in the sky.
![2022-03-07_22 07 33](https://user-images.githubusercontent.com/15375876/157127603-0a6f1fba-0159-4edc-85e7-967482c80354.png)

**Comment by FalsePattern** [comment]
I cannot reproduce this issue with SpongeMixins + Triangulator + MicdoodleCore + GC Core + GC Planets on my system

**Comment by DarianLStephens** [comment]
I just did the exact same thing, with the same issue.
![2022-03-11_10 38 51](https://user-images.githubusercontent.com/15375876/157773720-405dd878-c862-415d-81b7-62b138a2238c.png)

Maybe it's a graphics card or driver thing?

**Comment by FalsePattern** [comment]
Could you send the `fml-client-latest.log` file? It probably contains some info about what might be failing

**Comment by DarianLStephens** [comment]
[fml-client-latest.log](https://github.com/FalsePattern/Triangulator/files/8228011/fml-client-latest.log)

**Comment by FalsePattern** [comment]
I'm unable to reproduce this issue neither on an AMD nor an NVIDIA GPU, it looks like a very system-specific issue.

I can only suggest updating and/or reinstalling your graphics drivers, and turning off any overlays such as discord, rivatuner, etc.
