### ISSUE TITLE
Neodymium compat is NOT a lie,but crash still

### ISSUE THREAD

**Issue by iamsoNewBee** [FalsePattern/Triangulator#34]
[minecraft-exported-crash-info-2022-09-19T07-46-08.zip](https://github.com/FalsePattern/Triangulator/files/9595507/minecraft-exported-crash-info-2022-09-19T07-46-08.zip)

**Comment by quentin452** [comment]
what the problem is me i don't have problem between neodymium and triangulator

**Comment by iamsoNewBee** [comment]
> 

BUT CRASH HAPPENED WHEN I ADDED THEM TOGETHER

> what the problem is, me i don't have problem between neodymium and triangulator

STRANGE .I JUST TEST THEM AGA
[minecraft-exported-crash-info-2022-09-19T23-03-42.zip](https://github.com/FalsePattern/Triangulator/files/9600139/minecraft-exported-crash-info-2022-09-19T23-03-42.zip)
IN AND EVERYTHING GOSE WELL.BUT THERE IS ANOTHER CRASH HAPPENING IN MY FULL MOD PAKE.

**Comment by quentin452** [comment]
do you have modslist?

**Comment by quentin452** [comment]
i see you have optifine try deleting optifine , and add archaicfix , and enable in archaicfix config

enableThreadedChunkUpdates
enableOcclusionTweaks

**Comment by iamsoNewBee** [comment]
<img width="912" alt="image" src="https://user-images.githubusercontent.com/98573273/191050505-ef5916d7-6e2e-48ca-ad1a-d8ed1e0caeaf.png">
<img width="885" alt="image" src="https://user-images.githubusercontent.com/98573273/191050564-d358cbb1-dcfd-4d5a-b0ae-b227ebd632f9.png">

**Comment by iamsoNewBee** [comment]
> i see you have optifine try deleting optifine , and add archaicfix , and enabling in archaicfix config https://github.com/embeddedt/ArchaicFix enableThreadedChunkUpdates enableOcclusionTweaks

i didnt add optifine(?),and it will crash if i add archaicfix.

**Comment by quentin452** [comment]
in your crash report i watch in some lines optifine

**Comment by quentin452** [comment]
> 

hum , what is the problem with archaicfix?

**Comment by iamsoNewBee** [comment]
> hum , what is the problem with archaicfix?

[minecraft-exported-crash-info-2022-09-19T23-12-46.zip](https://github.com/FalsePattern/Triangulator/files/9600233/minecraft-exported-crash-info-2022-09-19T23-12-46.zip)

**Comment by quentin452** [comment]
archaic fix is incompatible with dragonapi

**Comment by iamsoNewBee** [comment]
OH EVERYTHING IS INCOMPATIBLE WITH DRAGONAPI LOL

**Comment by iamsoNewBee** [comment]
CRYING
<img width="388" alt="image" src="https://user-images.githubusercontent.com/98573273/191054081-79e62a99-3cd1-4ba4-b0ba-7f8149d9f60d.png">

**Comment by quentin452** [comment]
is possible to give me your modpack by mega.nz or something to try to find incompat with triangulator etc...

**Comment by iamsoNewBee** [comment]
> is possible to give me your modpack by mega.nz or something to try to find incompat with triangulator etc...? archaic fix is incompatible with dragonapi,cofhtweaks and attention with aquatweaks mod (this mods destroy performance)
[
](https://mega.nz/file/r7QTyB5A#yTjDzmH9LvAS3EjMPRGvnbYgZrKLBrQKcxkJzSpaUMw)
IT CONTAINS MY MODS AND CONFIGS AND IT DOESNT LEAD TO CRASH.U CAN TRY TO REPLACE triangulator OR gasstation WITH IT`S NEW VISION.

**Comment by quentin452** [comment]
ok
 thx

**Comment by quentin452** [comment]
I'll send you a txt of what I did and I'll send you a mega.nz in return as soon as I'm done

**Comment by iamsoNewBee** [comment]
> I'll send you a txt of what I did and I'll send you a mega.nz in return as soon as I'm done

GREAT APPRECIATE !  :D

**Comment by quentin452** [comment]
The modpack work correctly , but i need to fix a spam logs and nei display issue
I will eat

**Comment by iamsoNewBee** [comment]
> i

THE UNNECCESSARY ISSUES COULD BE IGNORED.BY THE WAY ,HOW DID U MAKE IT?

**Comment by quentin452** [comment]
some incompat mods

**Comment by quentin452** [comment]
changelogs for the moment
[changelogs.md](https://github.com/FalsePattern/Triangulator/files/9607260/changelogs.md)

**Comment by quentin452** [comment]
i think nei have no display issue , i think this is intentional by nei easy search

**Comment by iamsoNewBee** [comment]
UNEXPECTED

**Comment by quentin452** [comment]
:D

**Comment by quentin452** [comment]
![Capture d’écran_2022-09-20_14-05-04](https://user-images.githubusercontent.com/42176772/191252940-9d569f61-6fc1-4f8c-8bb0-6b2dcce84e90.png)

**Comment by iamsoNewBee** [comment]
> ![Capture d’écran_2022-09-20_14-05-04](https://user-images.githubusercontent.com/42176772/191252940-9d569f61-6fc1-4f8c-8bb0-6b2dcce84e90.png) Nei easy search make this

IT`S NOT A ISSUE MAYBE.IT`S USED FOR SHOWING RECENT SEARCHED ITEMS LOL

**Comment by quentin452** [comment]
ok

**Comment by iamsoNewBee** [comment]
> final changelogs :
> 
> [changelogs.md](https://github.com/FalsePattern/Triangulator/files/9607491/changelogs.md)
> 
> fixed modpack 1.7.10 :
> 
> https://mega.nz/file/S8kTHILb#DHYPu7KeWwEJFp8Qv2yyNu1rKtUiSvi7dKdchiEV8Ms

THX FOR YOUR EFFORTS!

**Comment by quentin452** [comment]
> > final changelogs :
> > [changelogs.md](https://github.com/FalsePattern/Triangulator/files/9607491/changelogs.md)
> > fixed modpack 1.7.10 :
> > https://mega.nz/file/S8kTHILb#DHYPu7KeWwEJFp8Qv2yyNu1rKtUiSvi7dKdchiEV8Ms
> 
> THX FOR YOUR EFFORTS!

i think you need to delete enviromine too , i got crash caused by enviromine

**Comment by quentin452** [comment]
i think you can close issue?

**Comment by iamsoNewBee** [comment]
> i think you can close the issue?

WONDERFUL WORK! (and a nice skin XD)
