### ISSUE TITLE
Crash when using with Archaicfix

### ISSUE THREAD

**Issue by Zilacon** [FalsePattern/Triangulator#36]
Getting these errors on start up
[crash-2022-09-21_09.35.42-client.txt](https://github.com/FalsePattern/Triangulator/files/9618701/crash-2022-09-21_09.35.42-client.txt)
[crash-2022-09-21_09.29.59-client.txt](https://github.com/FalsePattern/Triangulator/files/9618702/crash-2022-09-21_09.29.59-client.txt)

Any solution to this?
Thanks.

**Comment by Zilacon** [comment]
> 

If you look at the crash logs:
	UCHI	gasstation{0.3.3} [GasStation] (00gasstation-mc1.7.10-0.3.3 (1).jar) 

Ive already done that.

**Comment by quentin452** [comment]
delete mixingasm and spongemixin

**Comment by Zilacon** [comment]
![Screenshot_3228](https://user-images.githubusercontent.com/3002248/191567431-fe74f779-d7e4-48b6-aaf2-6935929681e6.png)
![Screenshot_3227](https://user-images.githubusercontent.com/3002248/191567435-b4420516-7c01-41cb-ad34-fe066ca1a2af.png)

???????????????????????

**Comment by quentin452** [comment]
and mixingasm is in gasstation

**Comment by Zilacon** [comment]
I know, i read everything on many of your mods before adding them to my client.
Including the issues.

**Comment by quentin452** [comment]
https://github.com/FalsePattern/Triangulator/files/9618702/crash-2022-09-21_09.29.59-client.txt

i found spongemixin and mixingasm here

**Comment by Zilacon** [comment]
But thats gas station?
	UCHIJ	spongemixins{1.5.0} [SpongeMixins] (00gasstation-mc1.7.10-0.3.3 (1).jar) 
	UCHIJ	mixingasm{0.2.2} [Mixingasm] (00gasstation-mc1.7.10-0.3.3 (1).jar)

**Comment by quentin452** [comment]
ah ok

**Comment by quentin452** [comment]
watch if your cofh core mods is named like this CoFHCore-[1.7.10]3.1.4-329

**Comment by Zilacon** [comment]
:|

**Comment by quentin452** [comment]
https://github.com/embeddedt/ArchaicFix/releases/tag/0.3.2

**Comment by quentin452** [comment]
idk

**Comment by quentin452** [comment]
lqst update of modpack 5 days ago , archaic fix 3 days ago

**Comment by Zilacon** [comment]
Alright clients starting now, just wish they would fix support for thermos so i could use it on my server...

**Comment by Zilacon** [comment]
Yeah, but thats by choice.
As far as i see, every mod in existence supports hybrid servers but ArchiacFix.
So you cant really say its a problem with the server.

**Comment by Zilacon** [comment]
Ive already seen that, and yet my statement stands.
I can download any "performance" mod for any version 1.5.2/1.6.4/1.7.10/1.12.2/1.16.5 and they all will launch on the hybrid software i used for servers.
So like i said, incompatibility for hybrid servers is by choice. Things that arent compatible with the server could easily just be disabled once it detects bukkit/spigot, which ive seen many others do.

**Comment by quentin452** [comment]
did i say it wasn't by choice? :D
