### ISSUE TITLE
In fact, my game is all triangles

### ISSUE THREAD

**Issue by mcmso** [FalsePattern/Triangulator#7]
![QQ截图20220311152557](https://user-images.githubusercontent.com/46519955/157821811-b860755f-d3dc-4937-a787-c5e16c4e9ec3.png)
![QQ截图20220311152435](https://user-images.githubusercontent.com/46519955/157821818-0f9f045d-e5b7-45da-982b-46c9a9577195.png)
![QQ截图20220311152519](https://user-images.githubusercontent.com/46519955/157821820-f830f4f9-f78a-4924-be9d-a737dde38b28.png)
[2022-03-11-1.log.gz](https://github.com/FalsePattern/Triangulator/files/8229964/2022-03-11-1.log.gz)
[latest.log](https://github
[fml-client-latest.zip](https://github.com/FalsePattern/Triangulator/files/8229970/fml-client-latest.zip)
.com/FalsePattern/Triangulator/files/8229965/latest.log)

I know it shouldn't be, but he's so funny

LOL

**Comment by FalsePattern** [comment]
Try turning off optifine shaders, it does some extremely heavy modifications to the same part of the render code that Triangulator injects into.
